### ISSUE TITLE
Wont run if "&" is in the path.

### ISSUE THREAD

**Issue by Zolo101** [foreshadow/atom-python-run#38]
### Every time I press F5 or F6 to run my python code, I get this message. ![screenshot_24](https://user-images.githubusercontent.com/27646575/27509884-586446c6-58fe-11e7-992e-a42f41ef010b.png)

My path has a `&` in it so I think that might be the problem. (eg. C:\Users\Adam&Coral\ would be C:\Users\Adam)

**Comment by foreshadow** [comment]
Got it. Due to my personal reasons, new versions will be not available until mid July.

**Comment by xovertheyearsx** [comment]
This issue should be resolved now with the new version.

**Comment by foreshadow** [comment]
@xovertheyearsx 
Actually it was not fixed until I replaced `sys.system` with `subprocess.call`.
Python document says `sys.system` is just a wrapper of windows C API, and it only accept a string which brings a lot of inconvenience. `subprocess.call` is recommended instead.
